### ISSUE TITLE
Using -1 as a marker for NA values

### ISSUE THREAD

**Issue by ammojamo** [Zoological-Society-of-London/rlpi#10]
The following lines check for -1 values in the PopN which are supposed to signify missing data:

https://github.com/Zoological-Society-of-London/rlpi/blob/2830f178d80f2a08e0358caca569b83626cd56ee/R/CalcLPI.R#L395-L398

However, PopN can sometimes contain legitimate -1 values, which should be included. This affects calculations on the sample dataset, to a minor degree.

To avoid this, NA should be used to represent missing values instead of -1 (or -99 as found in other parts of the codebase).

**Comment by robinfreeman** [comment]
This should now be fixed as of v0.0.3
