### ISSUE TITLE
Zero replace flag doesn't seem to do zero replacement

### ISSUE THREAD

**Issue by ammojamo** [Zoological-Society-of-London/rlpi#11]
I am presuming that ZERO_REPLACE_FLAG is intended to replace zeros, while OFFSET_ALL/OFFSET_DIFF is supposed to offset all values.

However, the code that handles ZERO_REPLACE_FLAG adds an offset to all values, rather than just replacing zeros as the name would suggest:

https://github.com/Zoological-Society-of-London/rlpi/blob/2830f178d80f2a08e0358caca569b83626cd56ee/R/CalcLPI.R#L146-L177

**Comment by robinfreeman** [comment]
I think this is a poorly named flag, it is doing as originally intended which is to add 1% of the mean of a population that contains zeros to all values. From Collen et al (2009) Conservation Biology: "One percent of the mean population measure value for the whole time series was added to all years in time series for which N was zero in any year."

We've updated the description to make this clearer:

"#' @param ZERO_REPLACE_FLAG  - This controls how zeros are dealt with. If this parameter is 0, then populations contining zeros will have a minimum value (1e-17) added to all value; If this flag is 1 then those populations will have +1\% of mean added to all values; If this flag is 2 then those pops will have +1 added. Default is 1, add 1% of the mean"
