### ISSUE TITLE
Handling of LAMBDA_MAX and LAMBDA_MIN

### ISSUE THREAD

**Issue by ammojamo** [Zoological-Society-of-London/rlpi#12]
The following code handling LAMBDA_MAX and LAMBDA_MIN contains two bugs:

https://github.com/Zoological-Society-of-London/rlpi/blob/2830f178d80f2a08e0358caca569b83626cd56ee/R/CalcLPI.R#L419-L462

1. PopLambda values that are equal to LAMBDA_MAX / LAMBDA_MIN are effectively ignored. For example on lines 425 and 426 for example, values greater than LAMBDA_MAX and less than LAMBDA_MAX are selected, but values equal to LAMBDA_MAX are not. This results in an incorrect SpeciesLambda value on line 438 or 440.
2. If there are PopLambda values above LAMBDA_MAX and below LAMBDA_MIN, but no values in between LAMBDA_MIN and LAMBDA_MAX, the code will result in SpeciesLambda = LAMBDA_MIN (line 445). Instead, the code should cap the PopLambda values to LAMBDA_MIN / LAMBDA_MAX as appropriate, and then take the mean.

**Comment by robinfreeman** [comment]
Fixed in v0.0.3
