### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by ammojamo** [Zoological-Society-of-London/rlpi#2]
Reviewing the source code, there seems to be a wide variety of naming styles in use e.g. camelCase, UpperCamelCase, snake_case, UPPER_CASE.

Is there a systematic reasoning for these naming styles? If not, how would you feel about adopting a consistent style? e.g. http://style.tidyverse.org/syntax.html

I'm not necessarily proposing cleaning everything up in one go, but maybe just following a 'leave it tidier than you found it' principle when working on the code.

**Comment by robinfreeman** [comment]
This would be great, this is partly from a mix of historic code. We've updated the files to use the tidyverse style using the 'styler' package, but this doesn't automatically change variables names, etc. It would need an overhaul to refactor, but would like to do this for a future version.
