### ISSUE TITLE
Installation fails with R 3.6.0

### ISSUE THREAD

**Issue by ammojamo** [Zoological-Society-of-London/rlpi#4]
Installing under R 3.6.0 with this command:
```
install_github("Zoological-Society-of-London/rlpi", dependencies=TRUE)
```
Fails with this error:

```
Error : (converted from warning) /private/var/folders/__/4mn3cntj09g5zt44rrf6jzw40000gp/T/RtmpOk1vn9/R.INSTALL808a7deecfcd/rlpi/man/CalcLPI.Rd:56: unexpected section header '\value'
ERROR: installing Rd objects failed for package ‘rlpi’
```

I believe this is caused by syntax issues in the documentation generated by roxygen.

**Comment by pennekampster** [comment]
Hi, 

many thanks for developing the rlpi package, this is great work! 

I have the same issue as reported here with R 3.6.0. Did anyone have time to look into this and check the PR send by ammojamo? 

Thanks!

**Comment by stefaniedeinet** [comment]
Hi, sorry for the delay and many thanks for fixing the issue! The changes have been checked and approved.
