### ISSUE TITLE
sourcing time series used in LPI and eventual goal for the `rlpi` package

### ISSUE THREAD

**Issue by ha0ye** [Zoological-Society-of-London/rlpi#6]
Hi,

I had a few questions about sourcing the time series used in the LPI project and your general plans for this package.

I see in the readme that there is a CSV version of the database on figshare, up through 2012, but as your project is ongoing, it seems reasonable that this R package is better-suited to obtaining the most up-to-date data. 

We are working on an infrastructure project to enable reproducible workflows on ecological time series (see https://weecology.github.io/MATSS/), and would like to include functionality to retrieve data used in the LPI (subject to whatever you can publicly share). We are planning to submit to CRAN, and so would be limited: if `rlpi` is not on CRAN, we cannot include it as a dependency.

Can you provide some guidance on these issues?

Thanks!

**Comment by valemarc** [comment]
Hi,

thank you for your interest in the LPI and sorry for the slow reply.  At the moment, there isn't an easy way to extract large quantities of data from the LPI, but we do make the dataset behind each Living Planet Report available online (except for those time-series that were provided to us under the agreement that they would be kept confidential). You can find the most recent version [here](http://www.livingplanetindex.org/projects?main_page_project=LivingPlanetReport&home_flag=1). 
The rpli package is not currently on CRAN so you might not be able to include it in your package as a dependency. Please let me know if you have any other question. You can also reach us at: LivingPlanetIndex@ioz.ac.uk.

Best wishes,

Valentina
