### ISSUE TITLE
LPI data from Figshare corrupted

### ISSUE THREAD

**Issue by yvanlebras** [Zoological-Society-of-London/rlpi#7]
Dear ZSL contact,

After trying to use LPI public data and rlpi package on Galaxy, I saw that the dataset published here https://figshare.com/articles/LPI_LPR2016data_public_csv/4300022 seems to be corrupted.

Notably around lines 2804 - 2807
![image](https://user-images.githubusercontent.com/7910679/77564948-c91cb000-6ec3-11ea-87b2-b199836decac.png)

Can you confirm that ?

**Comment by valemarc** [comment]
Hi Yvan,

thanks for getting in touch and for your interest in the LPI. I checked and there seems to be extra text in the field "method" in the row above the ones you can't see, which might be causing the problem. We hadn't realised because those rows appeared as normal in the csv file.

In case it's of interest, there is a more recent (2018) version of the LPI data at the bottom of this page: http://www.livingplanetindex.org/projects?main_page_project=LivingPlanetReport&home_flag=1. You will also find the link to our data policy there. Please make sure you read it.

Please don't hesitate to get in touch if you have any questions. You can also contact us at livingplanetindex@ioz.ac.uk.

Best wishes,

Valentina

**Comment by yvanlebras** [comment]
Thank you for your rapid feedback.

It appears to me that the 2016 fishare file is malfromatted (from R fread or MS Excel point of view), and looking at these particular ~2804 lines, it appears to me the line 2804 is truncated and the end of this line is at the start of line 2808.

Thank you for pointing me the 2018 version of the file. Looking at this version, it confirms what I am saying on the truncated 2804 line as here, the line is completed. It can be of interest to share this version of LPI data on a research data store like Zenodo / DRYAD or other no ? 

I am planning to share broadly this file as an example of what can be done reagarding EBV operationalization, creating index from raw data, EBV datasets and using EBV workflows. PERsonnaly I prefer having classical license like CC-BY (and your license seams to be very similar to CC-BY-NC-ND) and if possible open data compatible like CC-BY 4.0.

**Comment by valemarc** [comment]
Hi Yvan,

sorry for the slow reply. I have created a [Figshare repository](https://figshare.com/collections/Living_Planet_Report_data/4936584) and added both the 2016 and the 2018 file to it. We will add the data sets for future Living Planet Reports in there too so they are all in a central repository. You are welcome to use the data in accordance with the data policy, but the data file cannot be hosted elsewhere on a public site as users need to know the original source of the data and refer to the data policy when using the data. Would it possible for you to share the link to the repository instead?

We are always interested in hearing more about how researchers around the world are using our data, as there are often areas of overlap with what we are doing and therefore opportunities for collaboration. Given you are working on EBVs, we just thought you might find [this paper](https://onlinelibrary.wiley.com/doi/full/10.1111/brv.12359) interesting.

Best wishes,

Valentina

**Comment by yvanlebras** [comment]
Kissling et al 2017 is my bedside reading ;) And speaking with Daniel is always very interesting ;)

No problem for me to cite the original source (of course!), like this is made through CC-BY for example. Here the licence seems to be unclear for me.... so if there is a risk to make a mistake, I prefer don't use this kind of dataset as a showcase...
