### ISSUE TITLE
Check for constant PopN value

### ISSUE THREAD

**Issue by ammojamo** [Zoological-Society-of-London/rlpi#9]
The following line appears to be checking if the PopN values are constant and therefore GAM interpolation is unnecessary:

https://github.com/Zoological-Society-of-London/rlpi/blob/2830f178d80f2a08e0358caca569b83626cd56ee/R/CalcLPI.R#L200-L204

However, just because the mean equals the first value does not mean the time series is constant.

A better check would be:

```if(var(PopN) == 0)```

**Comment by robinfreeman** [comment]
Great! Now updated to if(var(PopN) == 0)
